# Set include paths from environment variables
SET(OPENCV_INCLUDE_DIR $ENV{OPENCV_DIR}/include CACHE FILEPATH "OpenCV include dir path")
INCLUDE_DIRECTORIES(${OPENCV_INCLUDE_DIR})
MESSAGE(STATUS "OpenCV include ${OPENCV_INCLUDE_DIR}")

SET(REALSENSE_INCLUDE_DIR $ENV{REALSENSE_DIR}/include CACHE FILEPATH "RealSense dir path")
INCLUDE_DIRECTORIES(${REALSENSE_INCLUDE_DIR})
MESSAGE(STATUS "RealSense include ${REALSENSE_INCLUDE_DIR}")

INCLUDE_DIRECTORIES(${Boost_INCLUDE_DIRS}) 
MESSAGE(STATUS "Boost include ${Boost_INCLUDE_DIRS}")

SET(KINECT2_INCLUDE_DIR $ENV{KINECTSDK20_DIR}/inc CACHE FILEPATH "Kinect 2 dir path")
INCLUDE_DIRECTORIES(${KINECT2_INCLUDE_DIR})
MESSAGE(STATUS "Kinect 2 include ${KINECT2_INCLUDE_DIR}")

set(KINECT_AZURE_INCLUDE_DIR ${KINECT_AZURE_SDK_DIR}/include CACHE FILEPATH "Kinect Azure dir path")
include_directories(${KINECT_AZURE_INCLUDE_DIR})
message(STATUS "Kinect Azure include dir ${KINECT_AZURE_INCLUDE_DIR}")


INCLUDE_DIRECTORIES(${OPENNI2_INCLUDE_DIRS})
MESSAGE(STATUS "OpenNI include ${OPENNI2_INCLUDE_DIRS}")